apiVersion: v1
kind: ConfigMap
metadata:
  name: lb-monitor-config
  namespace: messenger
data:
  POSTGRES_HOST: "host.docker.internal"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"
  REDIS_HOST: "host.docker.internal"
  REDIS_PORT: "6379"
  REDIS_CACHE_TTL: "60"
  UPDATE_INTERVAL: "30000"
  REDIS_URL: "redis://host.docker.internal:6379" 