apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: messenger
type: Opaque
stringData:
  secret: "JWTSecretKey123!@#"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: messenger
type: Opaque
stringData:
  host: "bexapaskey.beget.app:5432"
  database: "default_db"
  user: "cloud_user"
  password: "Md&7xKRB2RSn"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: messenger
type: Opaque
stringData:
  password: "RedisStrongPassword123!"

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: messenger
type: Opaque
stringData:
  username: ""
  password: "" 