apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-service-config
  namespace: messenger
data:
  PORT: "80"
  CORS_ORIGIN: "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-service
  namespace: messenger
  labels:
    app: swagger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-service
  template:
    metadata:
      labels:
        app: swagger-service
    spec:
      containers:
      - name: swagger-service
        image: docer2-swagger-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: swagger-service-config
              key: PORT
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: swagger-service-config
              key: CORS_ORIGIN
        volumeMounts:
        - name: swagger-docs
          mountPath: /etc/swagger-docs
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: swagger-docs
        configMap:
          name: swagger-config
          items:
          - key: user-service.yaml
            path: user-service.yaml
          - key: message-service.yaml
            path: message-service.yaml
          - key: call-service.yaml
            path: call-service.yaml
          - key: channel-service.yaml
            path: channel-service.yaml
          - key: notification-service.yaml
            path: notification-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-service
  namespace: messenger
spec:
  selector:
    app: swagger-service
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger-service-ingress
  namespace: messenger
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /api-docs
        pathType: Prefix
        backend:
          service:
            name: swagger-service
            port:
              name: http 